### ISSUE TITLE
[DOC] Zigbee Onboarding Roadmap Improvements

### ISSUE THREAD

**Issue by Jim-tech** [MarkDing/IoT-Developer-Boot-Camp#24]
**Describe the request**
Below are some comments on the draft of Zigbee Onboarding Roadmap.

**Recommended improvement**

- It's recommended to add a link to the resource if possible.
- It's recommended to add a serial number ahead of the resource item. 
- Do you think it's necessary to separate zigbee general knowledge and our solution? I think AN716/AN728 are more like our solution.

**Additional context**
NA.

@silabs-Haoyang

**Comment by MarkDing** [comment]
[Updated RoadMap](https://github.com/MarkDing/IoT-Developer-Boot-Camp-Wiki/blob/master/zigbee/Silicon%20Labs%20ZigBee%20Onboarding%20Roadmap.pdf)
