### ISSUE TITLE
[DOC] Zigbee Sleepy End Device Improvment

### ISSUE THREAD

**Issue by MarkDing** [MarkDing/IoT-Developer-Boot-Camp#27]
**Describe the request**
I have reviewed the PPTX not the lab section yet. Please check comments below. 

**Recommended improvement**
	1. [Slide 2 - Agenda] Missing contents of "Basic concepts->Finding and Binding"
	2. [Slide 3 - What are End Devices] The device type:RFD in network analyzer captured data doesn't look related with ED or SED
	3. [Slide 4 - What is Polling?] Why there are two Data requests in first second? And no response from CR for 2nd and 3rd second. Right?
	4. [Slide 5 - Polling as…from the parent] the "Mac" should be "MAC"
	5. [Slide 6 - Keepalive and time] Change "Mac" and "mac" to "MAC"; the arrow under "leave request" is not on the position. Can we show default value of "End Device Poll Timeout " in the note?
	6. [Slide 9 - Hands-on: Overview] The agenda is not like the agenda in Slide 2
	7. [Slide 9-13] All notes are same, cannot understand what is going on here. 
	8. [Slide 14,15 Debug Commands, Overview of Finding & Binding] It looks like using light and switch as example, not the sensor we talk in this slides. 
	9. [Slide 17, 18 - Finding & Binding…endpoint] The finding & binding procedure flow chart of target and initiator are the same except the highlight rectangle is different. Cannot tell what is difference between these two. 
	10. [Slide 20 - Debug Commands] Duplicate slide which is same as slide 14. 
	11. [Slide 21 - Sleeping] The notes isn't right for the contents of the slide.

**Comment by MarkDing** [comment]
1. [Page 2, 1.1 Check EmberZnet SDK] There is no MCU 5.8.4.0 in my installation but it is highlight by red box. That might confuse the beginner without this MCU info. 
	2. [Page 3, 2 Flash the program] Shall we mention that connect the WSTK board first before "Flash Programmer"?
	3. [Page 4, 2.4 Then in the next window…] Don't know which image should be programed into the flash. 
	4. [Page 5, 3 Build the bootloader] Build bootloader has been mentioned in preparatory course, Lab of day 1, might be we don't need it here. 
	5. [Page 10, 12. Save the modified project] We add press "Ctrl+S" or click on Save icon to save. 
	6. [Page 11, 5.1 Choose one WSTK] We should tell customer which sleepy ED file to be programed into the WSTK. We can emphasis again that we have a coordinator ready so that they can start joining the network. 
	7. [Page 11, 5.2 on the console…] We can emphasis again how to open the console. Beginner might has the chance to forget it. 
	8. [Page 11, 5.3 Use info command] After  joining the network, SED fall into sleep. I have to press button 1 to wake it up so that I can type info command. It is not clear whether join the right network. 
	9. [Page 11, 5.6 Start a capture with Network…] We can show how to start a capture by right click on the device. 
	10. [Page 11, 5.7 Start Energy Profiler…] We can show how to start the energy profiler. And SED keep wake unless you press button0. 
	11. [Page 15, 14. Click "Callbacks"] Click on "Expand Table" and then type "Main init" that can quickly locate which it is. Or we can show in which category we can find these call backs. 
	12. [Page 15, 15. Click "Includes" tab, scroll to the bottom].  We should emphasis to drag the scroll bar to the bottom. I tried to use middle wheel of mouse, it stops at one view and won't scroll to the bottom. 
	13. [Page 15, 17.b Add function ember…], the function missing "}". We should emphasis that the function is not generated in the callback file, user need to add it by themselves. 
	14. [Page 15, 17.c Add the following …adc] The #include “em_adc.h”should use "". Otherwise, the build cannot pass
	15. [Page 17, Test and observe the capture] Shall we emphasis the temperature we captured. Otherwise, it looks no difference from previous network analyzer capture result in page 11, 5.6 start a capture with network analyzer. 
	16. [Page 18, energy profiler] the average power consumption is 3.7 mA which is much higher than page 11

**Comment by ChengYuan-CY** [comment]
I have few comments on the hands-on documentations.
Hands-on, Zigbee Sleepy End Device
1. Add network key to the lab1

Hands-on, OTA Upgrading
1. [Page 11, 7 Build the new version client image] Remind the use to copy the new image to the ota-files folder.
2. [Page 14, step 5] If didn't see this kind of information, please execute the CLI below to check the image information.
plugin ota-storage reload
plugin ota-storage printImages
3. [Page 15, step 11] I get the error below after starting the OTA on the router device, after setting the ZCL Device Type as any HA Device, the problem gone.
T00000000:RX len 16, ep 01, clus 0x0019 (Over the Air Bootloading) FC 19 seq 04 cmd 02 payload[00 02 10 00 00 C8 00 00 00 B2 2F 03 00 ]
Drop cluster 0x0019 command 0x02 for endpoint 0x01 due to wrong profile: 0x0104
4. [Page 15, step 12] use the following command to check the firmware version after "upgrading the image".
